# Generated by Django 4.0.2 on 2022-02-05 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('matricule', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prenoms', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('dateNaisssance', models.DateField(blank=True, verbose_name='Date de naissance')),
                ('lieuNaissance', models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('H', 'Homme'), ('F', 'Femme')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='classeroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refClasse', models.IntegerField(unique=True, verbose_name='Référence')),
                ('libClasse', models.CharField(choices=[('3A', '3è MA'), ('3B', '3è MB'), ('4A', '4è MA'), ('4B', '4è MB'), ('5A', '5è MA'), ('5B', '5è MB'), ('6A', '6è MA'), ('6A', '6è MB')], max_length=25, unique=True, verbose_name='Classe')),
                ('niveau', models.CharField(choices=[('3è', 'Troisième'), ('4è', 'Quatrième'), ('5è', 'Cinquième'), ('6è', 'Sixième')], max_length=25, verbose_name='Niveau')),
                ('nbTables', models.IntegerField(verbose_name='Nombre de tables')),
                ('surveillant', models.CharField(blank=True, max_length=200, verbose_name='Surveillant')),
                ('profPrincipal', models.CharField(blank=True, max_length=200, verbose_name='Prof principal')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matricule', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prenoms', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('dateNaisssance', models.DateField(blank=True, verbose_name='Date de naissance')),
                ('lieuNaissance', models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
            ],
        ),
    ]
