# Generated by Django 4.0.2 on 2022-02-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classeroom',
            name='libClasse',
            field=models.CharField(choices=[('3A', '3è MA'), ('3B', '3è MB'), ('4A', '4è MA'), ('4B', '4è MB'), ('5A', '5è MA'), ('5B', '5è MB'), ('6A', '6è MA'), ('6B', '6è MB')], max_length=25, unique=True, verbose_name='Classe'),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(choices=[('2020-2021', '2021'), ('2021-2022', '2022'), ('2022-2023', '2023')], max_length=9)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.classeroom')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='inscriptions',
            field=models.ManyToManyField(to='eleves.Affectation'),
        ),
    ]
