# Generated by Django 4.0.2 on 2022-02-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_alter_classeroom_libclasse_affectation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='inscriptions',
        ),
    ]
