# Generated by Django 4.0.2 on 2022-02-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_remove_student_inscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('affectation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.affectation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.student')),
            ],
        ),
    ]
