# Generated by Django 4.0.2 on 2022-02-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0004_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dateNaisssance',
        ),
        migrations.AddField(
            model_name='student',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lieuNaissance',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de naissance'),
        ),
    ]
