# Generated by Django 4.0.2 on 2022-02-05 22:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0006_alter_inscription_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='affectation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.affectation'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDeb', models.DateField(default=datetime.datetime.today, verbose_name='Début')),
                ('dateFin', models.DateField(default=datetime.datetime.today, verbose_name='Fin')),
                ('heureDeb', models.TimeField(default=datetime.datetime.now, verbose_name='De')),
                ('heureFin', models.TimeField(default=datetime.datetime.now, verbose_name='A')),
                ('type', models.CharField(blank=True, max_length=25, verbose_name='Type Absence')),
                ('justified', models.BooleanField(default=False, verbose_name='Justifiée')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.student')),
            ],
        ),
    ]
